version: '3'
services:
  tunnelingus:
    image: tunnelingus
    build: ./
    container_name: tunnelingus
    restart: always
    ports:
      - "2222:22"
    environment:
      - VIRTUAL_HOST=${LETSENCRYPT_HOST}
      - VIRTUAL_PORT=8080 # needs to be higher than 1024 for ssh to be able to reverse forward
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
      
networks:
  default:
    external:
      name: ${NETWORK}
